# Generated by Django 6.0.4 on 2026-05-06 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareBoxApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('mister', 'Mister'), ('woman', 'Woman'), ('diverse', 'Diverse')], max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('level_of_care', models.PositiveSmallIntegerField()),
                ('street_address', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('zip_code', models.CharField(max_length=20)),
                ('different_delivery_address', models.BooleanField(default=False)),
                ('delivery_street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_area', models.CharField(blank=True, max_length=120, null=True)),
                ('delivery_city', models.CharField(blank=True, max_length=120, null=True)),
                ('delivery_zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=30)),
                ('consultation_answer', models.CharField(max_length=255)),
                ('consultation_reason', models.TextField(blank=True, null=True)),
                ('already_provided_with_care_aids', models.BooleanField(default=False)),
                ('insurance_type', models.CharField(choices=[('legally_insured', 'Legally Insured'), ('privately_insured', 'Privately Insured'), ('local_social_welfare_office', 'Local/Social Welfare Office')], max_length=50)),
                ('insurance_name', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance_number', models.CharField(blank=True, max_length=100, null=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('signed_cost_assumption', models.BooleanField(default=False)),
                ('signed_supplier_change', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('application_month', models.CharField(max_length=7)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carebox_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareBoxApplicationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carebox.careboxapplication')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='CareBoxFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction', models.CharField(max_length=50)),
                ('information_helpful', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='carebox.careboxapplication')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carebox_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
